auto: true

markdown: rdiscount
pygments: true
#paginate: 8
permalink: /:title

title: 大脸的博客
url: http://blog.11010.net
feed: /atom.xml
author_info: <a href="http://blog.11010.net/">、大脸</a>
highlighter: rouge
